---
sidebar: sidebar 
permalink: concept-worm.html 
keywords: worm, write once, read many, snaplock, retain, retention, period, cloud worm, worm storage, tiering 
summary: 'Cloud Volumes ONTAP 시스템에서 WORM(Write Once, Read Many) 스토리지를 활성화하여 지정된 보존 기간 동안 수정되지 않은 형식으로 파일을 보존할 수 있습니다. 클라우드 WORM 스토리지는 SnapLock 기술을 기반으로 하며, 이는 WORM 파일이 파일 레벨에서 보호됨을 의미합니다.' 
---
= WORM 스토리지
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 시스템에서 WORM(Write Once, Read Many) 스토리지를 활성화하여 지정된 보존 기간 동안 수정되지 않은 형식으로 파일을 보존할 수 있습니다. 클라우드 WORM 스토리지는 SnapLock 기술을 기반으로 하며, 이는 WORM 파일이 파일 레벨에서 보호됨을 의미합니다.

WORM 기능은 추가 비용 없이 라이센스 BYOL(Bring Your Own License) 및 마켓플레이스 가입과 함께 사용할 수 있습니다. NetApp 영업 담당자에게 문의하여 현재 라이센스에 WORM를 추가하십시오.



== WORM 스토리지의 작동 방식

파일이 WORM 스토리지에 커밋되면 보존 기간이 만료된 후에도 수정할 수 없습니다. 변조 방지 시계는 WORM 파일의 보존 기간이 경과된 시점을 결정합니다.

보존 기간이 경과한 후에는 더 이상 필요하지 않은 파일을 삭제해야 합니다.



== WORM 스토리지를 활성화하는 중입니다

WORM 스토리지의 활성화 방법은 사용 중인 Cloud Volumes ONTAP 버전에 따라 다릅니다.



=== 버전 9.10.1 이상

Cloud Volumes ONTAP 9.10.1부터 볼륨 수준에서 WORM을 활성화 또는 비활성화할 수 있는 옵션이 있습니다.

새 Cloud Volumes ONTAP 작업 환경을 생성할 때 WORM 스토리지를 설정하거나 해제하라는 메시지가 표시됩니다.

* 작업 환경을 생성할 때 WORM 스토리지를 활성화하면 BlueXP에서 생성한 모든 볼륨에서 WORM이 활성화됩니다. 그러나 ONTAP System Manager 또는 ONTAP CLI를 사용하여 WORM이 비활성화된 볼륨을 생성할 수 있습니다.
* 작업 환경을 생성할 때 WORM 스토리지를 사용하지 않도록 설정하는 경우 BlueXP , ONTAP System Manager 또는 ONTAP CLI에서 생성하는 모든 볼륨에서 WORM이 사용되지 않도록 설정됩니다.




=== 버전 9.10.0 이하

새로운 작업 환경을 생성할 때 Cloud Volumes ONTAP 시스템에서 WORM 스토리지를 활성화할 수 있습니다. BlueXP에서 생성한 모든 볼륨에서 WORM이 활성화되어 있습니다. 개별 볼륨에서 WORM 스토리지를 비활성화할 수 없습니다.



== WORM에 파일 커밋 중

애플리케이션을 사용하여 NFS 또는 CIFS를 통해 WORM에 파일을 커밋하거나 ONTAP CLI를 사용하여 파일을 WORM에 자동으로 커밋할 수 있습니다. 또한 WORM 추가 가능 파일을 사용하여 로그 정보와 같이 점증적으로 기록된 데이터를 보존할 수 있습니다.

Cloud Volumes ONTAP 시스템에서 WORM 스토리지를 활성화한 후에는 모든 WORM 스토리지 관리에 ONTAP CLI를 사용해야 합니다. 자세한 지침은 을 참조하십시오 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-arch-con/home.html["ONTAP 설명서"^].



== Cloud Volumes ONTAP 작업 환경에서 WORM 활성화

BlueXP 에서 Cloud Volumes ONTAP 작업 환경을 생성할 때 WORM 스토리지를 활성화할 수 있다. 생성 중에 작업 환경에서 WORM이 활성화되지 않은 경우에도 WORM을 활성화할 수 있습니다. 활성화한 후에는 WORM을 비활성화할 수 없습니다.

.이 작업에 대해
* WORM은 ONTAP 9.10.1 이상에서 지원됩니다.
* ONTAP 9.11.1 이상에서는 백업이 포함된 웜이 지원됩니다.


.단계
. Canvas 페이지에서 WORM을 활성화할 작업 환경의 이름을 두 번 클릭합니다.
. 개요 탭에서 기능 패널을 클릭한 다음 * WORM * 옆에 있는 연필 아이콘을 클릭합니다.
+
시스템에서 WORM이 이미 활성화되어 있으면 연필 아이콘이 비활성화됩니다.

. WORM * 페이지에서 클러스터 규정 준수 시계의 보존 기간을 설정합니다.
+
자세한 내용은 을 https://docs.netapp.com/us-en/ontap/snaplock/initialize-complianceclock-task.html["ONTAP 설명서: 규정 준수 시계를 초기화합니다"^]참조하십시오.

. Set * 를 클릭합니다.


.작업을 마친 후
기능 패널에서 * WORM * 의 상태를 확인할 수 있습니다. WORM이 활성화되면 SnapLock 라이센스가 클러스터에 자동으로 설치됩니다. ONTAP System Manager에서 SnapLock 라이센스를 볼 수 있습니다.



== WORM 파일을 삭제하는 중입니다

보존 기간 동안 권한이 있는 삭제 기능을 사용하여 WORM 파일을 삭제할 수 있습니다.

자세한 내용은 을 https://docs.netapp.com/us-en/ontap/snaplock/delete-worm-files-concept.html["ONTAP 설명서"^]참조하십시오.



== WORM 및 데이터 계층화

새로운 Cloud Volumes ONTAP 9.8 시스템 이상을 생성할 때 데이터 계층화와 WORM 스토리지를 함께 사용할 수 있습니다. WORM 스토리지를 통한 데이터 계층화를 사용하면 데이터를 클라우드의 오브젝트 저장소에 계층화할 수 있습니다.

데이터 계층화와 WORM 스토리지 모두에 대한 설정 방법은 다음과 같습니다.

* 오브젝트 스토리지로 계층화되어 있는 데이터에는 ONTAP WORM 기능이 포함되지 않습니다. 엔드 투 엔드 WORM 기능을 보장하려면 버킷 권한을 올바르게 설정해야 합니다.
* 오브젝트 스토리지로 계층화된 데이터에는 WORM 기능이 없습니다. 즉, 기술적으로 버킷 및 컨테이너에 대한 모든 액세스 권한이 있는 사람은 ONTAP에 의해 계층화된 오브젝트를 이동 및 삭제할 수 있습니다.
* WORM 및 계층화를 활성화한 후에는 Cloud Volumes ONTAP 9.8로의 되돌리기 또는 다운그레이드가 차단됩니다.




== 제한 사항

* Cloud Volumes ONTAP의 WORM 스토리지는 "신뢰할 수 있는 스토리지 관리자" 모델로 운영됩니다. WORM 파일은 변경 또는 수정으로부터 보호되지만, 만료되지 않은 WORM 데이터가 포함된 볼륨에도 클러스터 관리자가 볼륨을 삭제할 수 있습니다.
* 신뢰할 수 있는 스토리지 관리자 모델 외에도 Cloud Volumes ONTAP의 WORM 스토리지는 "신뢰할 수 있는 클라우드 관리자" 모델에서도 암시적으로 작동합니다. 클라우드 관리자는 클라우드 공급자에서 직접 클라우드 스토리지를 제거 또는 편집하여 만료 날짜 이전에 WORM 데이터를 삭제할 수 있습니다.


.관련 정보
* link:reference-worm-snaplock.html["WORM 스토리지를 위한 변조 방지 스냅샷 복사본을 생성합니다"]

