---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: 'freemium, professional, essentials, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go, keystone flex, keystone, cloud backup, digital wallet, bluexp license conversion for node based, license end of support (EOS) node-based, end of availability (EOA) of node-based' 
summary: Cloud Volumes ONTAP에는 몇 가지 라이센스 옵션이 있습니다. 각 옵션을 사용하여 요구 사항에 맞는 구성을 선택할 수 있습니다. 
---
= Cloud Volumes ONTAP에 대한 라이센싱입니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP에는 몇 가지 라이센스 옵션이 있습니다. 각 옵션을 사용하여 요구사항에 맞는 소비 모델을 선택할 수 있습니다.



== 라이센스 개요

신규 고객은 다음과 같은 라이선스 옵션을 사용할 수 있습니다.

용량 기반 라이센스:: 프로비저닝된 용량을 기준으로 NetApp 계정의 여러 Cloud Volumes ONTAP 시스템에 대한 비용 지불 애드온 클라우드 데이터 서비스를 구매할 수 있는 기능이 포함되어 있습니다. 용량 기반 라이센스의 소비 모델에 대한 자세한 내용은 을 link:concept-licensing-charging.html["용량 기반 라이센스에 대해 자세히 알아보십시오"]참조하십시오.
Keystone 구독:: 고가용성(HA) 쌍을 위한 원활한 하이브리드 클라우드 경험을 제공하는 용량제 구독 기반 서비스입니다.


다음 섹션에서는 이러한 각 옵션에 대해 자세히 설명합니다.


NOTE: 라이센스가 없는 경우 라이센스가 부여된 기능을 사용할 수 없습니다.



== 용량 기반 라이센스

용량 기반 라이센스 패키지를 사용하여 Cloud Volumes ONTAP/TiB 용량 단위로 비용을 지불할 수 있습니다. 라이센스는 NetApp 계정에 연결되며, 라이센스를 통해 사용할 수 있는 용량이 충분한 경우 라이센스에 대해 여러 시스템을 청구할 수 있습니다.

예를 들어, 20TiB 라이센스 1개를 구입하고 Cloud Volumes ONTAP 시스템 4개를 배포한 다음 각 시스템에 5TiB 볼륨을 할당하여 총 20TiB를 할당할 수 있습니다. 용량은 해당 계정에 구축된 각 Cloud Volumes ONTAP 시스템의 볼륨에 사용할 수 있습니다.

용량 기반 라이센스는 _package_ 형식으로 제공됩니다. Cloud Volumes ONTAP 시스템을 구축할 때 비즈니스 요구 사항에 따라 여러 라이센스 패키지 중에서 선택할 수 있습니다.


NOTE: BlueXP에서 관리되는 제품 및 서비스의 실제 사용량 및 계측은 항상 GiB 및 TiB 단위로 계산되지만 GB/GiB와 TB/TiB라는 용어는 같은 의미로 사용됩니다. 이는 클라우드 마켓플레이스 목록, 가격 견적, 목록 설명 및 기타 지원 문서에 반영되어 있습니다.



=== 패키지

Cloud Volumes ONTAP에 사용할 수 있는 용량 기반 패키지는 다음과 같습니다. 용량 기반 라이센스 패키지에 대한 자세한 내용은 을 link:concept-licensing-charging.html["용량 기반 라이센스에 대해 자세히 알아보십시오"]참조하십시오.

다음과 같은 용량 기반 패키지가 있는 지원되는 VM 유형 목록은 을 참조하십시오.

ifdef::azure[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Azure에서 지원되는 구성"^]


endif::azure[]

ifdef::gcp[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Google Cloud에서 지원되는 구성"^]


endif::gcp[]



==== 프리모늄

NetApp에서 무료로 모든 Cloud Volumes ONTAP 기능을 제공합니다(클라우드 공급자 요금은 여전히 적용됨). Freemium 패키지는 다음과 같은 특징을 가지고 있습니다.

* 라이센스 또는 계약이 필요하지 않습니다.
* NetApp의 지원은 포함되지 않습니다.
* Cloud Volumes ONTAP 시스템당 프로비저닝된 용량 500GiB로 제한됩니다.
* NetApp 계정당 Freemium 오퍼링으로 모든 클라우드 공급자에 대해 최대 10대의 Cloud Volumes ONTAP 시스템을 사용할 수 있습니다.
* Cloud Volumes ONTAP 시스템의 프로비저닝된 용량이 500GiB를 초과하면 BlueXP 는 시스템을 Essentials 패키지로 변환합니다.
+
시스템이 Essentials 패키지로 변환되는 즉시 해당 패키지에 link:concept-licensing-charging.html#minimum-charge["최소 충전"]적용됩니다.

+
Essentials 패키지로 변환된 Cloud Volumes ONTAP 시스템은 프로비저닝된 용량이 500GiB 미만으로 줄어든 경우에도 Freemium으로 다시 전환할 수 없습니다. 용량 용량이 500GiB 미만인 다른 시스템은 Freemium에 남아 있습니다(Freemium 오퍼링을 사용하여 구축한 경우).





==== 필수 요소

고객은 다양한 구성으로 용량별로 지불할 수 있습니다.

* Cloud Volumes ONTAP 구성 선택:
+
** 단일 노드 또는 HA 시스템
** DR(재해 복구)을 위한 파일 및 블록 스토리지 또는 보조 데이터


* NetApp의 클라우드 데이터 서비스를 추가 비용으로 이용할 수 있습니다




==== 전문가입니다

무제한 백업을 통해 모든 유형의 Cloud Volumes ONTAP 구성에 대한 용량별 지불.

* 모든 Cloud Volumes ONTAP 구성에 대한 라이센스를 제공합니다
+
동일한 속도로 운영 및 2차 볼륨의 용량을 충전하는 단일 노드 또는 HA

* BlueXP 백업 및 복구를 사용하는 무제한 볼륨 백업이 포함되지만 프로페셔널 패키지를 사용하는 Cloud Volumes ONTAP 시스템에 대해서만 포함됩니다.
+

NOTE: BlueXP  백업 및 복구를 위해서는 PAYGO(Pay-as-you-go) 구독이 필요하지만 이 서비스 사용에 따른 비용은 발생하지 않습니다. BlueXP  백업 및 복구의 라이센스 설정에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html["BlueXP 백업 및 복구에 대한 라이센스를 설정합니다"^]참조하십시오.

* NetApp의 클라우드 데이터 서비스를 추가 비용으로 이용할 수 있습니다




=== 용량 기반 라이센스의 가용성

Cloud Volumes ONTAP 시스템용 PAYGO 및 BYOL 라이센스를 사용하려면 BlueXP  커넥터를 가동 및 실행해야 합니다. 자세한 내용은 을 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#impact-on-cloud-volumes-ontap["커넥터에 대해 자세히 알아보십시오"^]참조하십시오.


NOTE: NetApp BYOL 라이선스 구매, 연장 및 갱신을 제한했습니다. 자세한 내용은  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Cloud Volumes ONTAPP 에 대한 BYOL 라이선싱의 제한된 가용성"^] .



=== 시작하는 방법

용량 기반 라이센스를 시작하는 방법에 대해 알아보십시오.

ifdef::aws[]

* link:task-set-up-licensing-aws.html["AWS에서 Cloud Volumes ONTAP에 대한 라이센스 설정"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Azure에서 Cloud Volumes ONTAP에 대한 라이센스를 설정합니다"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Google Cloud에서 Cloud Volumes ONTAP에 대한 라이센스를 설정합니다"]


endif::gcp[]



== Keystone 구독

OpEx 소비 모델을 선호하는 투자자들에게 원활한 하이브리드 클라우드 경험을 제공하여 선불 CapEx 또는 임대를 지불하는 종량제 구독 기반 서비스입니다.

충전은 Keystone 가입 중 하나 이상의 Cloud Volumes ONTAP HA 쌍에서 대해 확정된 용량 크기를 기준으로 합니다.

각 볼륨에 대해 프로비저닝된 용량은 주기적으로 Keystone 가입 시 할당된 용량과 비교되며, Keystone 가입 시 초과요금이 부과됩니다.

link:https://docs.netapp.com/us-en/keystone-staas/index.html["NetApp Keystone에 대해 자세히 알아보십시오"^].



=== 지원되는 구성

Keystone 구독은 HA 쌍으로 지원됩니다. 현재 단일 노드 시스템에서는 이 라이센스 옵션이 지원되지 않습니다.



=== 용량 제한

각 개별 Cloud Volumes ONTAP 시스템은 디스크를 통해 최대 2개의 PiB 용량을 지원하고 오브젝트 스토리지로 계층화합니다.



=== 시작하는 방법

Keystone 가입을 시작하는 방법 알아보기:

ifdef::aws[]

* link:task-set-up-licensing-aws.html["AWS에서 Cloud Volumes ONTAP에 대한 라이센스 설정"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Azure에서 Cloud Volumes ONTAP에 대한 라이센스를 설정합니다"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Google Cloud에서 Cloud Volumes ONTAP에 대한 라이센스를 설정합니다"]


endif::gcp[]



== 노드 기반 라이센스

노드 기반 라이센스는 이전 세대 라이센스 모델로, 노드별로 Cloud Volumes ONTAP에 대한 라이센스를 부여할 수 있도록 지원합니다. 신규 고객은 이 라이센스 모델을 사용할 수 없습니다. 노드별 충전은 위에서 설명한 용량 기준 충전 방법으로 대체되었습니다.

NetApp은 노드 기반 라이센싱의 EOA(End of Availability) 및 지원(EOS)을 계획했습니다. EOA 및 EOS 후에 노드 기반 라이센스를 용량 기반 라이센스로 변환해야 합니다.

자세한 내용은 을 https://mysupport.netapp.com/info/communications/CPC-00589.html["고객 연락: CPC-00589"^]참조하십시오.



=== 노드 기반 라이센스의 공급 중지

2024년 11월 11일부터 노드 기반 라이선스의 제한된 제공이 종료되었습니다.  노드 기반 라이선싱에 대한 지원은 2024년 12월 31일에 종료됩니다.

EOA 날짜를 초과하여 연장되는 유효한 노드 기반 계약이 있는 경우 계약이 만료될 때까지 라이센스를 계속 사용할 수 있습니다. 계약이 만료되면 용량 기반 라이센스 모델로 전환해야 합니다. Cloud Volumes ONTAP 노드에 대한 장기 계약이 없는 경우 EOS 날짜 전에 전환을 계획하는 것이 중요합니다.

다음 표에서 각 라이센스 유형 및 EOA가 라이센스 유형에 미치는 영향에 대해 자세히 알아보십시오.

[cols="2*"]
|===
| 사용권 유형 | EOA 이후 영향 


 a| 
BYOL(Bring Your Own License)을 통해 구매한 유효한 노드 기반 라이센스
 a| 
라이센스는 만료 시까지 유효합니다. 사용되지 않는 기존 노드 기반 라이센스를 사용하여 새로운 Cloud Volumes ONTAP 시스템을 구축할 수 있습니다.



 a| 
BYOL을 통해 노드 기반 라이센스가 만료되었습니다
 a| 
이 라이센스를 사용하여 새 Cloud Volumes ONTAP 시스템을 배포할 수 없습니다. 기존 시스템은 계속 작동할 수 있지만 EOS 날짜 이후에는 시스템에 대한 지원이나 업데이트를 받지 못합니다.



 a| 
PAYGO 서브스크립션이 있는 유효한 노드 기반 라이센스입니다
 a| 
EOS 날짜 이후에는 용량 기반 라이센스로 전환할 때까지 NetApp 지원을 더 이상 받지 않습니다.

|===
.예외사항
NetApp은 특정 상황을 특별히 고려해야 함을 인식하며, 노드 기반 라이센스의 EOA 및 EOS는 다음과 같은 경우에 적용되지 않습니다.

* 미국 공공 부문 고객
* 비공개 모드로 배포
* 중국 지역에 AWS에서 Cloud Volumes ONTAP를 구축했습니다


이러한 특정 시나리오에서 NetApp은 계약 의무 및 운영 요구 사항을 준수하는 고유한 라이센스 요구 사항을 해결하기 위한 지원을 제공합니다.


NOTE: 이러한 시나리오에서도 새로운 노드 기반 라이센스와 라이센스 갱신은 승인일로부터 최대 1년 동안 유효합니다.



== 사용권 변환

BlueXP 를 사용하면 라이센스 변환 툴을 통해 노드 기반 라이센스를 용량으로 원활하게 전환할 수 있습니다. 노드 기반 라이센스의 EOA에 대한 자세한 내용은 을 link:concept-licensing.html#end-of-availability-of-node-based-licenses["노드 기반 라이센스의 공급 중지"]참조하십시오.

전환하기 전에 두 라이센스 모델 간의 차이점을 숙지하는 것이 좋습니다. 노드 기반 라이센스에는 각 ONTAP 인스턴스에 대해 고정 용량이 포함되어 있어 유연성이 제한될 수 있습니다. 반면, 용량 기반 라이센스는 여러 인스턴스에 걸쳐 공유 스토리지 풀을 지원하므로 유연성을 높이고 리소스 활용도를 최적화하며 워크로드를 재배포할 때 재정적 불이익을 받을 가능성을 줄입니다. 용량 기반 충전은 변화하는 스토리지 요구 사항에 맞춰 원활하게 조정됩니다.

이 변환을 수행하는 방법은 을 link:task-convert-node-capacity.html["Cloud Volumes ONTAP 노드 기반 라이센스를 용량 기반 라이센스로 변환합니다"]참조하십시오.


NOTE: 시스템을 용량 기반에서 노드 기반 라이센스로 변환할 수 없습니다.
