---
sidebar: sidebar 
permalink: reference-worm-snaplock.html 
keywords: WORM, SnapLock, Snapshot copies, 
summary: 'Cloud Volumes ONTAP 시스템에서 WORM(Write Once, Read Many) 파일의 변조 방지 스냅샷 복사본을 생성하여 특정 보존 기간 동안 수정되지 않은 형태로 스냅샷을 유지할 수 있습니다.' 
---
= WORM 스토리지를 위한 변조 방지 스냅샷 복사본을 생성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 시스템에서 WORM(Write Once, Read Many) 파일의 변조 방지 스냅샷 복사본을 생성하여 특정 보존 기간 동안 수정되지 않은 형태로 스냅샷을 유지할 수 있습니다. 이 기능은 SnapLock 기술을 기반으로 하며 추가적인 데이터 보호 및 규정 준수를 제공합니다.

.시작하기 전에
스냅샷 복사본을 생성하는 데 사용하는 볼륨이 SnapLock 볼륨인지 확인합니다. 볼륨에 대한 SnapLock 보호 설정에 대한 자세한 내용은 를 https://docs.netapp.com/us-en/ontap/snaplock/snaplock-config-overview-concept.html["ONTAP 설명서: SnapLock 구성"^]참조하십시오.

.단계
. SnapLock 볼륨에서 스냅샷 복사본을 생성합니다. CLI 또는 System Manager를 사용하여 스냅샷 복사본을 생성하는 방법에 대한 자세한 내용은 를 https://docs.netapp.com/us-en/ontap/data-protection/manage-local-snapshot-copies-concept.html["ONTAP 설명서: 로컬 스냅샷 복사본 관리 개요"^]참조하십시오.
+
스냅샷 복사본은 볼륨의 WORM 속성을 상속하여 무단 변경을 방지합니다. 기본 SnapLock 기술을 사용하면 지정된 보존 기간이 경과할 때까지 스냅샷이 편집 및 삭제되지 않도록 보호됩니다.

. 이러한 스냅샷을 편집해야 하는 경우 보존 기간을 수정할 수 있습니다. 자세한 내용은 를 https://docs.netapp.com/us-en/ontap/snaplock/set-retention-period-task.html#set-the-default-retention-period["ONTAP 설명서: 보존 시간을 설정합니다"^]참조하십시오.



NOTE: 스냅샷 복사본은 특정 보존 기간 동안 보호되지만, Cloud Volumes ONTAP의 WORM 스토리지는 "신뢰할 수 있는 스토리지 관리자" 모델로 작동하므로 클러스터 관리자가 소스 볼륨을 삭제할 수 있습니다. 또한 신뢰할 수 있는 클라우드 관리자가 클라우드 스토리지 리소스에서 운영하는 방식으로 WORM 데이터를 삭제할 수 있습니다.
