---
sidebar: sidebar 
permalink: task-saz-feature.html 
keywords: Microsoft Azure feature, HA in SAZ, single availability zone, Azure feature, Virtual Machine Scale Sets in Flexible mode 
summary: SAZ에 HA를 배포하려면 이 Microsoft Azure 기능을 활성화하십시오. 
---
= 단일 가용 영역에 대해 VMOrchestrator ZonalMultiFD를 사용하도록 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
LRS(Local-Redundant Storage) 단일 가용 영역에 VM 인스턴스를 배포하려면 `Microsoft.Compute/VMOrchestratorZonalMultiFD` 구독에 Microsoft 기능을 활성화해야 합니다. HA 모드에서 이 기능은 동일한 가용 영역에 있는 별도의 장애 도메인에 노드를 쉽게 구축할 수 있도록 합니다.

이 기능을 활성화하지 않으면 영역 배포가 수행되지 않고 이전 LRS 비영역 배포가 적용됩니다.

단일 가용 영역의 VM 배포에 대한 자세한 내용은 을 link:concept-ha-azure.html["Azure의 고가용성 쌍"]참조하십시오.

"소유자" Privileges를 가진 사용자로 다음 단계를 수행합니다.

.단계
. Azure 포털에서 Azure Cloud Shell에 액세스합니다. 자세한 내용은 을 https://learn.microsoft.com/en-us/azure/cloud-shell/get-started/["Microsoft Azure 설명서: Azure Cloud Shell 시작하기"^]참조하십시오.
.  `Microsoft.Compute/VMOrchestratorZonalMultiFD`다음 명령을 실행하여 기능에 등록합니다.
+
[]
====
AZ 계정 세트 -s_<Azure_subscription_name_or_ID>_az 기능 레지스터--name VMOrchestrator ZonalMultiFD--namespace Microsoft.Compute

====
. 등록 상태 및 출력 샘플을 확인합니다.
+
[]
====
AZ 기능 show -n VMOrchestrator ZonalMultiFD -- namespace Microsoft.Compute {"id":"/subscriptions/_<ID>_/providers/microsoft.features/providers/Microsoft.Compute/features/VMOrchestratorZonalMultiFD", "name":"Microsoft.Compute/VMOrchestratorZonalMultiFD","properties":{"state":{"state"},"type":"microsoft.features/features/provides

====

