---
sidebar: sidebar 
permalink: task-deploy-aws-shared-vpc.html 
keywords: shared vpc, aws shared vpc, vpc sharing, shared subnet, deploy shared vpc, assume role 
summary: 9.11.1 릴리즈부터 VPC 공유를 지원하는 AWS에서 Cloud Volumes ONTAP HA 쌍이 지원됩니다. VPC 공유를 사용하면 서브넷을 다른 AWS 계정과 공유할 수 있습니다. 이 구성을 사용하려면 AWS 환경을 설정한 다음 API를 사용하여 HA 쌍을 구축해야 합니다. 
---
= 공유 서브넷에 HA 쌍 구축
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
9.11.1 릴리즈부터 VPC 공유를 지원하는 AWS에서 Cloud Volumes ONTAP HA 쌍이 지원됩니다. VPC 공유를 사용하면 서브넷을 다른 AWS 계정과 공유할 수 있습니다. 이 구성을 사용하려면 AWS 환경을 설정한 다음 API를 사용하여 HA 쌍을 구축해야 합니다.

와 함께 https://aws.amazon.com/blogs/networking-and-content-delivery/vpc-sharing-a-new-approach-to-multiple-accounts-and-vpc-management/["VPC 공유"^]Cloud Volumes ONTAP HA 구성은 다음 두 계정에 분산됩니다.

* 네트워킹을 소유하는 VPC 소유자 계정(VPC, 서브넷 및 경로 테이블)
* 참가자 계정으로, EC2 인스턴스가 공유 서브넷에 구축됩니다(여기에는 2개의 HA 노드와 중재자가 포함됨).


여러 가용성 영역에 배포된 Cloud Volumes ONTAP HA 구성의 경우 HA 중재자가 VPC 소유자 계정의 라우트 테이블에 쓸 수 있는 특정 권한이 필요합니다. 중재자가 추정할 수 있는 IAM 역할을 설정하여 이러한 권한을 제공해야 합니다.

.단계
. IAM 역할을 생성합니다.
+
.. Cloud Volumes ONTAP용 EC2 인스턴스를 배포하려는 참가자 계정의 IAM 콘솔로 이동합니다.
.. 액세스 관리에서 * 역할 > 역할 만들기 * 를 클릭하고 단계를 따라 역할을 만듭니다.
+
다음을 수행하십시오.

+
*** 신뢰할 수 있는 엔터티 유형 * 에서 * AWS 계정 * 을 선택합니다.
*** 다른 AWS 계정 * 을 선택하고 VPC 소유자 계정의 ID를 입력합니다.
*** Cloud Manager IAM 정책을 사용하여 정책을 생성합니다. 이 정책은 에서 사용할 수 있습니다 https://mysupport.netapp.com/site/info/cloud-manager-policies["Cloud Manager 정책 페이지"^].


.. HA Pair를 배포할 때 API 요청에 붙여넣을 수 있도록 IAM 역할의 Role ARN을 복사합니다.


. VPC 소유자 계정의 서브넷을 참가자 계정과 공유합니다.
+
이 단계는 공유 서브넷에 HA 쌍을 구축하는 데 필요합니다.

+
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html#vpc-sharing-share-subnet["AWS 설명서: 서브넷을 공유합니다"^]

. VPC 소유자 계정에서 Cloud Volumes ONTAP용 보안 그룹을 생성합니다.
+
link:reference-security-groups.html["Cloud Volumes ONTAP의 보안 그룹 규칙을 참조하십시오"]. HA 중재자를 위한 보안 그룹을 만들 필요는 없습니다. Cloud Manager가 이 작업을 수행합니다.

. API를 사용하여 새 Cloud Volumes ONTAP 작업 환경을 만들고 "haParams" 개체의 "assumeRoleArn" 필드를 전달합니다.
+
[source, json]
----
"haParams": {
     “assumeRoleArn”: “arn:aws:iam::642991768967:role/mediator_role_assume_fromdev”
}
----
+
https://docs.netapp.com/us-en/cloud-manager-automation/cm/overview.html["Cloud Volumes ONTAP API에 대해 자세히 알아보십시오"^]


