---
sidebar: sidebar 
permalink: task-getting-started-aws-c2s.html 
keywords: commercial cloud services, c2s, secret cloud, top secret cloud, aws secret region, BlueXP 
summary: 표준 AWS 지역과 마찬가지로, AWS Secret Cloud 및 Top Secret Cloud 환경에서 BlueXP를 사용하여 클라우드 스토리지에 엔터프라이즈급 기능을 제공하는 Cloud Volumes ONTAP를 구축할 수 있습니다. AWS Secret Cloud 및 Top Secret Cloud 지역은 미국 고유의 폐쇄형 지역입니다 이 페이지의 지침은 AWS Secret Cloud 및 Top Secret Cloud 지역 사용자에게만 적용됩니다. 
---
= AWS Secret Cloud 또는 AWS Top Secret Cloud에 Cloud Volumes ONTAP을 구현합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
표준 AWS 지역과 마찬가지로 에서 BlueXP를 사용할 수 있습니다 link:https://aws.amazon.com/federal/secret-cloud/["AWS 비밀 클라우드"^] 및 IN link:https://aws.amazon.com/federal/top-secret-cloud/["AWS Top Secret Cloud의 약어입니다"^] Cloud Volumes ONTAP 구축: 클라우드 스토리지에 엔터프라이즈급 기능을 제공합니다. AWS Secret Cloud 및 Top Secret Cloud는 미국 고유의 폐쇄형 지역입니다 이 페이지의 지침은 AWS Secret Cloud 및 Top Secret Cloud 지역 사용자에게만 적용됩니다.

.시작하기 전에
시작하기 전에 AWS Secret Cloud 및 Top Secret Cloud에서 지원되는 버전을 검토하고 BlueXP의 프라이빗 모드에 대해 알아보십시오.

* AWS Secret Cloud 및 Top Secret Cloud에서 지원되는 다음 버전을 검토하십시오.
+
** Cloud Volumes ONTAP 9.12.1 P2
** 커넥터의 버전 3.9.32
+
Connector는 AWS에서 Cloud Volumes ONTAP를 구축하고 관리하는 데 필요한 소프트웨어입니다. Connector 인스턴스에 설치된 소프트웨어에서 BlueXP에 로그인합니다. BlueXP용 SaaS 웹 사이트는 AWS Secret Cloud 및 Top Secret Cloud에서 지원되지 않습니다.



* 비공개 모드에 대해 알아봅니다
+
AWS Secret Cloud 및 Top Secret Cloud에서 BlueXP는 _private mode_로 작동합니다. 프라이빗 모드에서는 BlueXP SaaS 계층에 연결할 수 없습니다. 사용자는 SaaS 계층이 아닌 Connector에서 사용할 수 있는 웹 기반 콘솔에서 로컬로 BlueXP에 액세스할 수 있습니다.

+
비공개 모드의 작동 방식에 대한 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#private-mode["BlueXP 프라이빗 구축 모드"^].





== 1단계: 네트워킹을 설정한다

Cloud Volumes ONTAP가 제대로 작동할 수 있도록 AWS 네트워킹을 설정합니다.

.단계
. 커넥터 인스턴스 및 Cloud Volumes ONTAP 인스턴스를 시작할 VPC 및 서브넷을 선택합니다.
. VPC와 서브넷이 커넥터와 Cloud Volumes ONTAP 간의 연결을 지원하는지 확인합니다.
. VPC 엔드포인트를 S3 서비스로 설정합니다.
+
Cloud Volumes ONTAP의 콜드 데이터를 저비용 오브젝트 스토리지로 계층화하려는 경우 VPC 엔드포인트가 필요합니다.





== 2단계: 사용 권한을 설정합니다

Connector 및 Cloud Volumes ONTAP에 AWS Secret Cloud 또는 Top Secret Cloud에서 작업을 수행하는 데 필요한 권한을 제공하는 IAM 정책 및 역할을 설정합니다.

다음 각 항목에 대해 IAM 정책 및 IAM 역할이 필요합니다.

* 커넥터 인스턴스
* Cloud Volumes ONTAP 인스턴스
* HA 페어의 경우 Cloud Volumes ONTAP HA 중재자 인스턴스(HA 쌍을 구축하려는 경우)


.단계
. AWS IAM 콘솔로 이동하여 * Policies * 를 클릭합니다.
. Connector 인스턴스에 대한 정책을 만듭니다.
+

NOTE: AWS 환경에서 S3 버킷을 지원하기 위해 이러한 정책을 생성할 수 있습니다. 나중에 버킷을 생성할 때 버킷 이름 앞에 가 있는지 확인합니다 `fabric-pool-`. 이 요구 사항은 AWS Secret Cloud 및 Top Secret Cloud 지역 모두에 적용됩니다.

+
[role="tabbed-block"]
====
.비밀 영역
--
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:DescribeRouteTables",
                "ec2:DescribeImages",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:DescribeVolumes",
                "ec2:ModifyVolumeAttribute",
                "ec2:DeleteVolume",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:CreateSnapshot",
                "ec2:DeleteSnapshot",
                "ec2:DescribeSnapshots",
                "ec2:GetConsoleOutput",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DeleteTags",
                "ec2:DescribeTags",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "iam:PassRole",
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:ListInstanceProfiles",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:GetBucketTagging",
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets",
                "kms:List*",
                "kms:Describe*",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "ec2:DescribeInstanceAttribute",
                "ec2:CreatePlacementGroup",
                "ec2:DeletePlacementGroup"
            ],
            "Resource": "*"
        },
        {
            "Sid": "fabricPoolPolicy",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteBucket",
                "s3:GetLifecycleConfiguration",
                "s3:PutLifecycleConfiguration",
                "s3:PutBucketTagging",
                "s3:ListBucketVersions"
            ],
            "Resource": [
                "arn:aws-iso-b:s3:::fabric-pool*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:StartInstances",
                "ec2:StopInstances",
                "ec2:TerminateInstances",
                "ec2:AttachVolume",
                "ec2:DetachVolume"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/WorkingEnvironment": "*"
                }
            },
            "Resource": [
                "arn:aws-iso-b:ec2:*:*:instance/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AttachVolume",
                "ec2:DetachVolume"
            ],
            "Resource": [
                "arn:aws-iso-b:ec2:*:*:volume/*"
            ]
        }
    ]
}
----
--
.주요 비밀 지역
--
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:DescribeRouteTables",
                "ec2:DescribeImages",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:DescribeVolumes",
                "ec2:ModifyVolumeAttribute",
                "ec2:DeleteVolume",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:CreateSnapshot",
                "ec2:DeleteSnapshot",
                "ec2:DescribeSnapshots",
                "ec2:GetConsoleOutput",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DeleteTags",
                "ec2:DescribeTags",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "iam:PassRole",
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:ListInstanceProfiles",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:GetBucketTagging",
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets",
                "kms:List*",
                "kms:Describe*",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "ec2:DescribeInstanceAttribute",
                "ec2:CreatePlacementGroup",
                "ec2:DeletePlacementGroup"
            ],
            "Resource": "*"
        },
        {
            "Sid": "fabricPoolPolicy",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteBucket",
                "s3:GetLifecycleConfiguration",
                "s3:PutLifecycleConfiguration",
                "s3:PutBucketTagging",
                "s3:ListBucketVersions"
            ],
            "Resource": [
                "arn:aws-iso:s3:::fabric-pool*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:StartInstances",
                "ec2:StopInstances",
                "ec2:TerminateInstances",
                "ec2:AttachVolume",
                "ec2:DetachVolume"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/WorkingEnvironment": "*"
                }
            },
            "Resource": [
                "arn:aws-iso:ec2:*:*:instance/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AttachVolume",
                "ec2:DetachVolume"
            ],
            "Resource": [
                "arn:aws-iso:ec2:*:*:volume/*"
            ]
        }
    ]
}
----
--
====
. Cloud Volumes ONTAP에 대한 정책을 생성합니다.
+
[role="tabbed-block"]
====
.비밀 영역
--
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
        "Action": "s3:ListAllMyBuckets",
        "Resource": "arn:aws-iso-b:s3:::*",
        "Effect": "Allow"
    }, {
        "Action": [
            "s3:ListBucket",
            "s3:GetBucketLocation"
        ],
        "Resource": "arn:aws-iso-b:s3:::fabric-pool-*",
        "Effect": "Allow"
    }, {
        "Action": [
            "s3:GetObject",
            "s3:PutObject",
            "s3:DeleteObject"
        ],
        "Resource": "arn:aws-iso-b:s3:::fabric-pool-*",
        "Effect": "Allow"
    }]
}
----
--
.주요 비밀 지역
--
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
        "Action": "s3:ListAllMyBuckets",
        "Resource": "arn:aws-iso:s3:::*",
        "Effect": "Allow"
    }, {
        "Action": [
            "s3:ListBucket",
            "s3:GetBucketLocation"
        ],
        "Resource": "arn:aws-iso:s3:::fabric-pool-*",
        "Effect": "Allow"
    }, {
        "Action": [
            "s3:GetObject",
            "s3:PutObject",
            "s3:DeleteObject"
        ],
        "Resource": "arn:aws-iso:s3:::fabric-pool-*",
        "Effect": "Allow"
    }]
}
----
--
====
+
HA 쌍의 경우, Cloud Volumes ONTAP HA 쌍을 구축할 계획인 경우 HA 중재자에 대한 정책을 생성하십시오.

+
[source, json]
----
{
	"Version": "2012-10-17",
	"Statement": [{
			"Effect": "Allow",
			"Action": [
				"ec2:AssignPrivateIpAddresses",
				"ec2:CreateRoute",
				"ec2:DeleteRoute",
				"ec2:DescribeNetworkInterfaces",
				"ec2:DescribeRouteTables",
				"ec2:DescribeVpcs",
				"ec2:ReplaceRoute",
				"ec2:UnassignPrivateIpAddresses"
			],
			"Resource": "*"
		}
	]
}
----
. Amazon EC2 역할 유형으로 IAM 역할을 생성하고 이전 단계에서 생성한 정책을 첨부합니다.
+
.역할 생성:
정책과 유사하게 커넥터용 IAM 역할 하나와 Cloud Volumes ONTAP 노드용 IAM 역할 하나가 있어야 합니다.
HA 쌍의 경우: 정책과 유사하게 커넥터용 IAM 역할 1개, Cloud Volumes ONTAP 노드용 IAM 역할 1개, HA 중재자용 역할 1개(HA 쌍을 배포하려는 경우)가 있어야 합니다.

+
.역할 선택:
Connector 인스턴스를 실행할 때 Connector IAM 역할을 선택해야 합니다. BlueXP에서 Cloud Volumes ONTAP 작업 환경을 생성할 때 Cloud Volumes ONTAP의 IAM 역할을 선택할 수 있습니다.
HA 쌍의 경우 BlueXP에서 Cloud Volumes ONTAP 작업 환경을 생성할 때 Cloud Volumes ONTAP 및 HA 중재자의 IAM 역할을 선택할 수 있습니다.





== 3단계: AWS KMS를 설정합니다

Cloud Volumes ONTAP와 함께 Amazon 암호화를 사용하려는 경우 AWS 키 관리 서비스(KMS)에 대한 요구 사항이 충족되는지 확인합니다.

.단계
. 사용자 계정 또는 다른 AWS 계정에 활성 CMK(Customer Master Key)가 있는지 확인합니다.
+
CMK는 AWS로 관리되는 CMK 또는 고객이 관리하는 CMK가 될 수 있습니다.

. CMK가 Cloud Volumes ONTAP를 배포할 계정과 별도로 AWS 계정에 있는 경우 해당 키의 ARN을 얻어야 합니다.
+
Cloud Volumes ONTAP 시스템을 생성할 때 ARN을 BlueXP에 제공해야 합니다.

. Connector 인스턴스의 IAM 역할을 CMK의 주요 사용자 목록에 추가합니다.
+
이렇게 하면 Cloud Volumes ONTAP에서 CMK를 사용할 수 있는 BlueXP 권한이 부여됩니다.





== 4단계: 커넥터 설치 및 BlueXP 설정

BlueXP를 사용하여 AWS에 Cloud Volumes ONTAP을 구축하기 전에 먼저 BlueXP Connector를 설치하고 설정해야 합니다. BlueXP는 커넥터를 통해 공용 클라우드 환경(Cloud Volumes ONTAP 포함)의 리소스와 프로세스를 관리할 수 있습니다.

.단계
. PEM(Privacy Enhanced Mail) Base-64로 인코딩된 X.509 형식으로 CA(인증 기관)에서 서명한 루트 인증서를 받습니다. 인증서를 얻으려면 조직의 정책 및 절차를 참조하십시오.
+

NOTE: AWS Secret Cloud 지역의 경우 를 업로드해야 합니다 `NSS Root CA 2` Certificate 및 Top Secret Cloud의 경우 `Amazon Root CA 4` 인증서. 이러한 인증서만 업로드하고 전체 체인은 업로드하지 마십시오. 인증서 체인의 파일이 커서 업로드에 실패할 수 있습니다. 추가 인증서가 있는 경우 다음 단계에 설명된 대로 나중에 업로드할 수 있습니다.

+
설치 프로세스 중에 인증서를 업로드해야 합니다. BlueXP는 HTTPS를 통해 AWS로 요청을 보낼 때 신뢰할 수 있는 인증서를 사용합니다.

. 커넥터 인스턴스를 시작합니다.
+
.. BlueXP의 AWS Intelligence Community Marketplace 페이지로 이동합니다.
.. Custom Launch 탭에서 EC2 콘솔에서 인스턴스를 시작하는 옵션을 선택합니다.
.. 프롬프트에 따라 인스턴스를 구성합니다.
+
인스턴스를 구성할 때 다음 사항에 유의하십시오.

+
*** T3.xLarge를 권장합니다.
*** 권한을 설정할 때 생성한 IAM 역할을 선택해야 합니다.
*** 기본 스토리지 옵션을 유지해야 합니다.
*** Connector에 필요한 연결 방법은 SSH, HTTP, HTTPS입니다.




. Connector 인스턴스에 연결된 호스트에서 BlueXP를 설정합니다.
+
.. 웹 브라우저를 열고 를 입력합니다 https://_ipaddress_[] 여기서 _ipaddress_는 Connector를 설치한 Linux 호스트의 IP 주소입니다.
.. AWS 서비스 연결을 위한 프록시 서버를 지정합니다.
.. 1단계에서 얻은 인증서를 업로드합니다.
.. Set Up New BlueXP * 를 선택하고 화면의 지시에 따라 시스템을 설정합니다.
+
*** * 시스템 세부 정보 *: 커넥터 이름과 회사 이름을 입력합니다.
*** * 관리자 사용자 생성 *: 시스템에 대한 관리자 사용자를 생성합니다.
+
이 사용자 계정은 시스템에서 로컬로 실행됩니다. BlueXP를 통해 사용할 수 있는 auth0 서비스에 연결할 수 없습니다.

*** * 검토 *: 세부 정보를 검토하고 사용권 계약에 동의한 다음 * 설정 * 을 선택합니다.


.. CA 서명 인증서의 설치를 완료하려면 EC2 콘솔에서 Connector 인스턴스를 다시 시작합니다.


. Connector가 다시 시작된 후 설치 마법사에서 만든 관리자 사용자 계정을 사용하여 로그인합니다.




== 단계 5: (선택 사항) 개인 모드 인증서를 설치합니다

이 단계는 AWS Secret Cloud 및 Top Secret Cloud 지역의 경우 선택 사항이며, 이전 단계에서 설치한 루트 인증서와 별도로 추가 인증서가 있는 경우에만 필요합니다.

.단계
. 설치된 기존 인증서를 나열합니다.
+
.. ocCM 컨테이너 Docker ID(식별된 이름 "ds-occm-1")를 수집하려면 다음 명령을 실행합니다.
+
[source, CLI]
----
docker ps
----
.. occm 컨테이너 내부로 이동하려면 다음 명령을 실행합니다.
+
[source, CLI]
----
docker exec -it <docker-id> /bin/sh
----
.. "trust_store_password" 환경 변수에서 암호를 수집하려면 다음 명령을 실행합니다.
+
[source, CLI]
----
env
----
.. truststore에 설치된 모든 인증서를 나열하려면 다음 명령을 실행하고 이전 단계에서 수집한 암호를 사용합니다.
+
[source, CLI]
----
keytool -list -v -keystore occm.truststore
----


. 인증서를 추가합니다.
+
.. occm 컨테이너 Docker ID(식별된 이름 "ds-occm-1")를 수집하려면 다음 명령을 실행합니다.
+
[source, CLI]
----
docker ps
----
.. occm 컨테이너 내부로 이동하려면 다음 명령을 실행합니다.
+
[source, CLI]
----
docker exec -it <docker-id> /bin/sh
----
+
새 인증서 파일을 에 저장합니다.

.. "trust_store_password" 환경 변수에서 암호를 수집하려면 다음 명령을 실행합니다.
+
[source, CLI]
----
env
----
.. 인증서를 truststore에 추가하려면 다음 명령을 실행하고 이전 단계의 암호를 사용합니다.
+
[source, CLI]
----
keytool -import -alias <alias-name> -file <certificate-file-name> -keystore occm.truststore
----
.. 인증서가 설치되어 있는지 확인하려면 다음 명령을 실행합니다.
+
[source, CLI]
----
keytool -list -v -keystore occm.truststore -alias <alias-name>
----
.. ocCM 컨테이너를 종료하려면 다음 명령을 실행합니다.
+
[source, CLI]
----
exit
----
.. ocCM 컨테이너를 재설정하려면 다음 명령을 실행합니다.
+
[source, CLI]
----
docker restart <docker-id>
----




--

--


== 6단계: BlueXP 디지털 지갑에 라이센스를 추가합니다

NetApp에서 라이센스를 구매한 경우, 새로운 Cloud Volumes ONTAP 시스템을 생성할 때 라이센스를 선택할 수 있도록 BlueXP 디지털 지갑에 추가해야 합니다. 디지털 지갑에서 이 라이선스를 할당되지 않은 것으로 식별합니다.

.단계
. BlueXP 탐색 메뉴에서 * Governance > Digital Wallet * 을 선택합니다.
. Cloud Volumes ONTAP * 탭의 드롭다운에서 * 노드 기반 라이센스 * 를 선택합니다.
. 할당되지 않음 * 을 클릭합니다.
. 할당되지 않은 라이센스 추가 * 를 클릭합니다.
. 라이센스의 일련 번호를 입력하거나 라이센스 파일을 업로드하십시오.
. 아직 라이센스 파일이 없는 경우 netapp.com 에서 라이센스 파일을 수동으로 업로드해야 합니다.
+
.. 로 이동합니다 link:https://register.netapp.com/site/vsnr/register/getlicensefile["NetApp 라이센스 파일 생성기"^] 를 입력하고 NetApp Support 사이트 자격 증명을 사용하여 로그인합니다.
.. 비밀번호를 입력하고 제품을 선택한 다음 일련 번호를 입력하고 개인정보 보호정책을 읽고 동의했는지 확인한 다음 * 제출 * 을 클릭합니다.
.. 이메일 또는 직접 다운로드를 통해 serialnumber.nlf JSON 파일을 수신할지 여부를 선택합니다.


. 라이선스 추가 * 를 클릭합니다.


.결과
BlueXP는 디지털 지갑에 라이선스를 추가합니다. 라이센스는 새 Cloud Volumes ONTAP 시스템에 연결할 때까지 할당되지 않은 것으로 식별됩니다. 이렇게 되면 라이센스가 디지털 지갑의 BYOL 탭으로 이동합니다.



== 7단계: BlueXP에서 Cloud Volumes ONTAP를 시작합니다

BlueXP에 새로운 작업 환경을 생성하여 AWS Secret Cloud 및 Top Secret Cloud에서 Cloud Volumes ONTAP 인스턴스를 시작할 수 있습니다.

.시작하기 전에
HA 쌍의 경우 HA 중재자에게 키 기반 SSH 인증을 활성화하려면 키 쌍이 필요합니다.

.단계
. 작업 환경 페이지에서 * 작업 환경 추가 * 를 클릭합니다.
. 만들기 * 아래에서 Cloud Volumes ONTAP를 선택합니다.
+
HA의 경우: * 생성 * 에서 Cloud Volumes ONTAP 또는 Cloud Volumes ONTAP HA를 선택합니다.

. 마법사의 단계를 완료하여 Cloud Volumes ONTAP 시스템을 시작합니다.
+

CAUTION: 마법사를 통해 선택하는 동안 * 서비스 * 아래에서 * Data Sense & Compliance * 및 * Backup to Cloud * 를 선택하지 마십시오. 사전 구성된 패키지 * 에서 * 구성 변경 * 만 을 선택하고 다른 옵션을 선택하지 않았는지 확인합니다. 사전 구성된 패키지는 AWS Secret Cloud 및 Top Secret Cloud 지역에서 지원되지 않으며, 이 옵션을 선택하면 배포가 실패합니다.



.다수의 가용 영역에 Cloud Volumes ONTAP HA를 구축하기 위한 참고 사항
HA 쌍 마법사를 완료하면 다음을 유의하십시오.

* 여러 가용 영역(AZ)에 Cloud Volumes ONTAP HA를 구축할 때는 전송 게이트웨이를 구성해야 합니다. 자세한 내용은 을 link:task-setting-up-transit-gateway.html["AWS 전송 게이트웨이를 설정합니다"]참조하십시오.
* 발행 당시 AWS Top Secret Cloud에서 두 개의 AZ만 사용할 수 있었기 때문에 구성을 다음과 같이 배포합니다.
+
** 노드 1: 가용성 영역 A
** 노드 2: 가용성 영역 B
** 중재자: 가용성 영역 A 또는 B




.참고: 단일 노드 및 HA 노드 모두에 Cloud Volumes ONTAP를 구축하기 위한 참고 사항입니다
마법사를 완료하면 다음 사항에 유의하십시오.

* 생성된 보안 그룹을 사용하려면 기본 옵션을 그대로 두어야 합니다.
+
미리 정의된 보안 그룹에는 Cloud Volumes ONTAP가 제대로 작동하는 데 필요한 규칙이 포함됩니다. 사용자 고유의 사용이 필요한 경우 아래의 보안 그룹 섹션을 참조할 수 있습니다.

* AWS 환경을 준비할 때 생성한 IAM 역할을 선택해야 합니다.
* 기본 AWS 디스크 유형은 초기 Cloud Volumes ONTAP 볼륨에 사용됩니다.
+
이후 볼륨에 대해 다른 디스크 유형을 선택할 수 있습니다.

* AWS 디스크의 성능은 디스크 크기와 관련이 있습니다.
+
필요한 일관된 성능을 제공하는 디스크 크기를 선택해야 합니다. EBS 성능에 대한 자세한 내용은 AWS 설명서를 참조하십시오.

* 디스크 크기는 시스템의 모든 디스크에 대한 기본 크기입니다.
+

NOTE: 나중에 다른 크기가 필요한 경우 고급 할당 옵션을 사용하여 특정 크기의 디스크를 사용하는 Aggregate를 생성할 수 있습니다.



.결과
BlueXP에서 Cloud Volumes ONTAP 인스턴스를 시작합니다. 타임라인에서 진행 상황을 추적할 수 있습니다.



== 8단계: 데이터 계층화를 위한 보안 인증서를 설치합니다

AWS Secret Cloud 및 Top Secret Cloud 지역에서 데이터 계층화를 활성화하려면 보안 인증서를 수동으로 설치해야 합니다.

.시작하기 전에
. S3 버킷을 생성합니다.
+

NOTE: 버킷 이름 앞에 가 있는지 확인합니다 `fabric-pool-.` 예를 들어 `fabric-pool-testbucket`.

. 에 설치한 루트 인증서를 유지합니다 `step 4` 편리합니다.


.단계
. 에 설치한 루트 인증서의 텍스트를 복사합니다 `step 4`.
. CLI를 사용하여 Cloud Volumes ONTAP 시스템에 안전하게 연결합니다.
. 루트 인증서를 설치합니다. 를 눌러야 할 수도 있습니다 `ENTER` 키를 여러 번 누름:
+
[listing]
----
security certificate install -type server-ca -cert-name <certificate-name>
----
. 메시지가 표시되면 및 을 포함하여 복사된 전체 텍스트를 입력합니다 `----- BEGIN CERTIFICATE -----` 를 선택합니다 `----- END CERTIFICATE -----`.
. 나중에 참조할 수 있도록 CA 서명 디지털 인증서의 복사본을 보관합니다.
. CA 이름과 인증서 일련 번호를 유지합니다.
. AWS Secret Cloud 및 Top Secret Cloud 지역에 대한 객체 저장소 구성: `set -privilege advanced -confirmations off`
. 이 명령을 실행하여 개체 저장소를 구성합니다.
+

NOTE: 모든 아마존 리소스 이름(ARN)에는 접미사가 붙어야 합니다 `-iso-b`예를 들면, 입니다 `arn:aws-iso-b`. 예를 들어, 리소스에 지역이 있는 ARN이 필요한 경우 Top Secret Cloud의 경우 명명 규칙을 로 사용합니다 `us-iso-b` 의 경우 `-server` 깃발. AWS Secret Cloud의 경우 를 사용합니다 `us-iso-b-1`.

+
[listing]
----
storage aggregate object-store config create -object-store-name <S3Bucket> -provider-type AWS_S3 -auth-type EC2-IAM -server <s3.us-iso-b-1.server_name> -container-name <fabric-pool-testbucket> -is-ssl-enabled true -port 443
----
. 개체 저장소가 성공적으로 생성되었는지 확인합니다. `storage aggregate object-store show -instance`
. 오브젝트 저장소를 애그리게이트에 연결합니다. 모든 새로운 애그리게이트에 대해 이 작업을 반복해야 합니다. `storage aggregate object-store attach -aggregate <aggr1> -object-store-name <S3Bucket>`

