---
sidebar: sidebar 
permalink: task-manage-aggregates.html 
keywords: aggregates, delete aggregates, add disks, view aggregates 
summary: 디스크를 추가하고, 애그리게이트에 대한 정보를 확인하고, 삭제하여 애그리게이트를 직접 관리하십시오. 
---
= 애그리게이트 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
디스크를 추가하고, 애그리게이트에 대한 정보를 확인하고, 삭제하여 애그리게이트를 직접 관리하십시오.


CAUTION: 모든 디스크와 애그리게이트는 BlueXP에서 직접 생성 및 삭제해야 합니다. 다른 관리 도구에서 이러한 작업을 수행해서는 안 됩니다. 이렇게 하면 시스템 안정성에 영향을 주고 향후 디스크를 추가할 수 없도록 하며 중복 클라우드 공급자 비용을 생성할 수 있습니다.

.시작하기 전에
Aggregate를 삭제하려면 먼저 Aggregate의 볼륨을 삭제해야 합니다.

.이 작업에 대해
Aggregate에 공간이 부족할 경우 System Manager를 사용하여 볼륨을 다른 애그리게이트로 이동할 수 있습니다.

.단계
. 왼쪽 탐색 메뉴에서 * Storage > Canvas * 를 선택합니다.
. Canvas 페이지에서 집계를 관리할 Cloud Volumes ONTAP 작업 환경을 두 번 클릭합니다.
. 메뉴 아이콘을 클릭한 다음 * 고급 > 고급 할당 * 을 클릭합니다.
. 애그리게이트 관리:
+
[cols="30,70"]
|===
| 작업 | 조치 


| Aggregate에 대한 정보를 봅니다 | Aggregate를 선택하고 * Info * 를 클릭합니다. 


| 특정 Aggregate에 볼륨을 생성합니다 | 애그리게이트를 선택하고 * 볼륨 생성 * 을 클릭합니다. 


| Aggregate에 디스크를 추가합니다  a| 
.. Aggregate를 선택하고 * Add disks * 를 클릭합니다.
.. 추가할 디스크 수를 선택하고 * 추가 * 를 클릭합니다.
+

TIP: Aggregate의 모든 디스크는 동일한 크기여야 합니다.



ifdef::aws[]



| Amazon EBS Elastic Volumes를 지원하는 애그리게이트의 용량을 늘립니다  a| 
.. 애그리게이트를 선택하고 * 용량 증가 * 를 클릭합니다.
.. 추가할 추가 용량을 입력한 다음 * 추가 * 를 클릭합니다.
+
Aggregate의 용량을 최소 256GiB 또는 애그리게이트 크기의 10% 이상으로 늘려야 합니다.

+
예를 들어 1.77TiB Aggregate가 있는 경우 10%는 181GiB입니다. 이 값이 256GiB보다 낮으므로 애그리게이트의 크기를 최소 256GiB까지 늘려야 합니다.



endif::aws[]



| 애그리게이트 삭제  a| 
.. 볼륨이 없는 Aggregate를 선택하고 * Delete * 를 클릭합니다.
.. 확인하려면 * 삭제 * 를 다시 클릭합니다.


|===

