---
sidebar: sidebar 
permalink: task-planning-your-config-gcp.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported machine types, supported virtual machines, supported vms, supported instances 
summary: Cloud Volumes ONTAP를 구축하면 워크로드 요구사항에 맞게 사전 구성된 시스템을 선택하거나 고유한 구성을 생성할 수 있습니다. 자신의 구성을 선택하는 경우 사용 가능한 옵션을 이해해야 합니다. 
---
= Google Cloud에서 Cloud Volumes ONTAP 구성을 계획하십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud에 Cloud Volumes ONTAP를 배포할 때 워크로드 요구 사항에 맞는 사전 구성된 시스템을 선택하거나 자신만의 구성을 만들 수 있습니다. 자신의 구성을 선택하는 경우 사용 가능한 옵션을 이해해야 합니다.



== Cloud Volumes ONTAP 라이센스를 선택합니다

Cloud Volumes ONTAP에는 몇 가지 라이센스 옵션이 있습니다. 각 옵션을 사용하여 요구사항에 맞는 소비 모델을 선택할 수 있습니다.

* link:concept-licensing.html["Cloud Volumes ONTAP의 라이센스 옵션에 대해 자세히 알아보십시오"]
* link:task-set-up-licensing-google.html["라이센스 설정 방법에 대해 알아보십시오"]




== 지원되는 지역을 선택하십시오

Cloud Volumes ONTAP는 대부분의 Google Cloud 지역에서 지원됩니다. https://bluexp.netapp.com/cloud-volumes-global-regions["지원되는 영역의 전체 목록을 봅니다"^]..



== 지원되는 시스템 유형을 선택합니다

Cloud Volumes ONTAP는 선택한 라이센스 유형에 따라 여러 가지 시스템 유형을 지원합니다.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["GCP에서 Cloud Volumes ONTAP에 지원되는 구성입니다"^]



== 스토리지 제한사항을 파악합니다

Cloud Volumes ONTAP 시스템의 물리적 용량 제한은 라이센스에 연결되어 있습니다. 추가 제한은 애그리게이트 및 볼륨 크기에 영향을 줍니다. 구성을 계획할 때 이러한 제한 사항을 숙지해야 합니다.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-gcp.html["GCP의 Cloud Volumes ONTAP에 대한 스토리지 제한입니다"^]



== GCP에서 시스템 크기를 조정합니다

Cloud Volumes ONTAP 시스템을 사이징하면 성능 및 용량 요구사항을 충족하는 데 도움이 될 수 있습니다. 시스템 유형, 디스크 유형 및 디스크 크기를 선택할 때 몇 가지 주요 사항을 알고 있어야 합니다.

기계 유형:: 에서 지원되는 기계 유형을 확인합니다 http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["Cloud Volumes ONTAP 릴리즈 노트"^] 지원되는 각 시스템 유형에 대한 자세한 내용은 Google에서 확인하십시오. 워크로드 요구 사항을 시스템 유형에 대한 vCPU 및 메모리 수와 일치시킵니다. 각 CPU 코어는 네트워킹 성능을 향상시킵니다.
+
--
자세한 내용은 다음을 참조하십시오.

* https://cloud.google.com/compute/docs/machine-types#n1_machine_types["Google Cloud 설명서: N1 표준 컴퓨터 유형"^]
* https://cloud.google.com/docs/compare/data-centers/networking#performance["Google Cloud 설명서: 성능"^]


--
GCP 디스크 유형입니다:: Cloud Volumes ONTAP용 볼륨을 생성할 때 Cloud Volumes ONTAP이 디스크에 사용하는 기본 클라우드 스토리지를 선택해야 합니다. 디스크 유형은 다음 중 하나일 수 있습니다.
+
--
* _Zonal SSD 영구 디스크_: SSD 영구 디스크는 높은 속도의 랜덤 IOPS가 필요한 워크로드에 가장 적합합니다.
* _Zonal Balanced 영구 디스크 _: 이 SSD는 GB당 더 낮은 IOPS를 제공하여 성능과 비용을 균형 있게 조정합니다.
* _Zonal Standard 영구 디스크_: 표준 영구 디스크는 경제적이며 순차적 읽기/쓰기 작업을 처리할 수 있습니다.
+
자세한 내용은 을 https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud 설명서: Zonal Persistent 디스크(Standard 및 SSD)"^]참조하십시오.



--
GCP 디스크 크기입니다:: Cloud Volumes ONTAP 시스템을 배포할 때 초기 디스크 크기를 선택해야 합니다. 그런 다음 BlueXP에서 시스템 용량을 관리할 수 있지만 자체적으로 집계를 구축하려는 경우 다음 사항에 유의하십시오.
+
--
* Aggregate의 모든 디스크는 동일한 크기여야 합니다.
* 성능을 고려하면서 필요한 공간을 결정합니다.
* 영구 디스크의 성능은 디스크 크기와 시스템에서 사용할 수 있는 vCPU 수에 따라 자동으로 확장됩니다.
+
자세한 내용은 다음을 참조하십시오.

+
** https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud 설명서: Zonal Persistent 디스크(Standard 및 SSD)"^]
** https://cloud.google.com/compute/docs/disks/performance["Google Cloud 설명서: 영구 디스크 및 로컬 SSD 성능 최적화"^]




--




== 기본 시스템 디스크를 봅니다

BlueXP는 사용자 데이터를 위한 스토리지 외에도 Cloud Volumes ONTAP 시스템 데이터(부팅 데이터, 루트 데이터, 핵심 데이터 및 NVRAM)를 위한 클라우드 스토리지를 구입합니다. 계획을 위해 Cloud Volumes ONTAP를 배포하기 전에 이러한 세부 정보를 검토하는 것이 도움이 될 수 있습니다.

* link:reference-default-configs.html#google-cloud-single-node["Google Cloud에서 Cloud Volumes ONTAP 시스템 데이터에 대한 기본 디스크를 봅니다"].
* https://cloud.google.com/compute/quotas["Google Cloud 문서: 리소스 할당량"^]
+
Google Cloud Compute Engine은 리소스 사용량에 대해 할당량을 적용하므로 Cloud Volumes ONTAP를 배포하기 전에 한계에 도달하지 않았는지 확인해야 합니다.




TIP: 커넥터에는 시스템 디스크도 필요합니다. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["커넥터의 기본 설정에 대한 세부 정보를 봅니다"^].



== 네트워킹 정보를 수집합니다

GCP에서 Cloud Volumes ONTAP를 배포할 때 가상 네트워크에 대한 세부 정보를 지정해야 합니다. 워크시트를 사용하여 관리자로부터 정보를 수집할 수 있습니다.

* 단일 노드 시스템에 대한 네트워크 정보 *

[cols="30,70"]
|===
| GCP 정보 | 귀사의 가치 


| 지역 |  


| Zone(영역) |  


| VPC 네트워크 |  


| 서브넷 |  


| 방화벽 정책(자체 사용 시) |  
|===
* 여러 존의 HA 쌍에 대한 네트워크 정보 *

[cols="30,70"]
|===
| GCP 정보 | 귀사의 가치 


| 지역 |  


| 노드 1의 영역 |  


| 노드 2의 영역 |  


| 중재자를 위한 구역 |  


| VPC-0 및 서브넷 |  


| VPC-1 및 서브넷 |  


| VPC-2 및 서브넷 |  


| VPC-3 및 서브넷 |  


| 방화벽 정책(자체 사용 시) |  
|===
* 단일 영역의 HA 쌍에 대한 네트워크 정보 *

[cols="30,70"]
|===
| GCP 정보 | 귀사의 가치 


| 지역 |  


| Zone(영역) |  


| VPC-0 및 서브넷 |  


| VPC-1 및 서브넷 |  


| VPC-2 및 서브넷 |  


| VPC-3 및 서브넷 |  


| 방화벽 정책(자체 사용 시) |  
|===


== 쓰기 속도를 선택합니다

BlueXP 를 사용하면 Google Cloud의 고가용성(HA) 쌍을 제외하고 Cloud Volumes ONTAP의 쓰기 속도 설정을 선택할 수 있습니다. 쓰기 속도를 선택하기 전에 고속 쓰기 속도를 사용할 때 정상 및 높음 설정의 차이점과 위험 및 권장 사항을 이해해야 합니다. link:concept-write-speed.html["쓰기 속도에 대해 자세히 알아보십시오"]..



== 볼륨 사용 프로필을 선택합니다

ONTAP에는 필요한 총 스토리지 양을 줄일 수 있는 몇 가지 스토리지 효율성 기능이 포함되어 있습니다. BlueXP에서 볼륨을 생성할 때 이러한 기능을 활성화하는 프로필이나 해당 기능을 비활성화하는 프로필을 선택할 수 있습니다. 사용할 프로파일을 결정하는 데 도움이 되도록 이러한 기능에 대해 자세히 알아 두어야 합니다.

NetApp 스토리지 효율성 기능은 다음과 같은 이점을 제공합니다.

씬 프로비저닝:: 에서는 실제 스토리지 풀에 있는 것보다 더 많은 논리적 스토리지를 호스트 또는 사용자에게 제공합니다. 스토리지 공간을 사전에 할당하는 대신 데이터가 기록될 때 스토리지 공간을 각 볼륨에 동적으로 할당합니다.
중복 제거:: 동일한 데이터 블록을 찾아 단일 공유 블록에 대한 참조로 대체하여 효율성을 향상시킵니다. 이 기술은 동일한 볼륨에 상주하는 중복된 데이터 블록을 제거하여 스토리지 용량 요구 사항을 줄여줍니다.
압축:: 1차, 2차 및 아카이브 스토리지의 볼륨 내에서 데이터를 압축하여 데이터를 저장하는 데 필요한 물리적 용량을 줄입니다.

