---
sidebar: sidebar 
permalink: task-accelerate-data-access.html 
keywords: flexcache, flexcache volumes, create a flexcache volume, provision flexcache, create flexcache volume 
summary: FlexCache 볼륨은 원본 또는 소스 볼륨에서 NFS 읽기 데이터를 캐싱하는 스토리지 볼륨입니다. 이후에 캐싱된 데이터를 읽으면 해당 데이터에 더 빠르게 액세스할 수 있습니다. 
---
= FlexCache 볼륨을 사용하여 데이터 액세스 가속화
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
FlexCache 볼륨은 원본(또는 소스) 볼륨에서 SMB 및 NFS 읽기 데이터를 캐싱하는 스토리지 볼륨입니다. 이후에 캐싱된 데이터를 읽으면 해당 데이터에 더 빠르게 액세스할 수 있습니다.

FlexCache 볼륨을 사용하면 데이터 액세스 속도를 높이거나 자주 액세스하는 볼륨에서 트래픽을 오프로드할 수 있습니다. FlexCache 볼륨은 원본 볼륨에 액세스하지 않고도 직접 데이터를 제공할 수 있으므로 클라이언트가 동일한 데이터에 반복적으로 액세스해야 할 때 성능을 개선할 수 있습니다. FlexCache 볼륨은 읽기 집약적인 시스템 워크로드에 적합합니다.

BlueXP는 를 사용하여 FlexCache 볼륨을 관리할 수 있는 기능을 제공합니다 link:https://docs.netapp.com/us-en/bluexp-volume-caching/index.html["BlueXP 볼륨 캐싱"^] 서비스.

ONTAP CLI 또는 ONTAP System Manager를 사용하여 FlexCache 볼륨을 생성하고 관리할 수도 있습니다.

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["빠른 데이터 액세스를 위한 FlexCache 볼륨 전원 가이드"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["System Manager에서 FlexCache 볼륨 생성"^]


BlueXP는 모든 새로운 Cloud Volumes ONTAP 시스템에 대한 FlexCache 라이센스를 생성합니다. 이 라이센스에는 500GiB 사용 제한이 포함됩니다.

video::PBNPVRUeT1o[youtube,width=848,height=480]


== 원본이 암호화된 경우 FlexCache로 작업합니다

원본 볼륨이 암호화된 Cloud Volumes ONTAP 시스템에서 FlexCache를 구성할 경우 FlexCache 볼륨이 암호화된 데이터에 올바르게 액세스하고 캐시할 수 있도록 추가 단계가 필요합니다.

.필요한 것
. * 암호화 설정 *: 소스 볼륨이 완전히 암호화되어 작동 중인지 확인합니다. Cloud Volumes ONTAP 시스템의 경우 클라우드용 키 관리 서비스와의 통합이 포함됩니다.


ifdef::aws[]

AWS의 경우 이는 일반적으로 AWS 키 관리 서비스(KMS)를 사용함을 의미합니다. 자세한 내용은 을 link:task-aws-key-management.html["AWS 키 관리 서비스로 키를 관리합니다"]참조하십시오.

endif::aws[]

ifdef::azure[]

Azure의 경우 NVE(NetApp Volume Encryption)용 Azure Key Vault를 설정해야 합니다. 자세한 내용은 을 link:task-azure-key-vault.html["Azure Key Vault를 사용하여 키를 관리합니다"]참조하십시오.

endif::azure[]

ifdef::gcp[]

Google Cloud의 경우 Google Cloud 키 관리 서비스입니다. 자세한 내용은 을 link:task-google-key-manager.html["Google의 클라우드 키 관리 서비스를 통해 키를 관리합니다"]참조하십시오.

endif::gcp[]

. * 키 관리 서비스 *: FlexCache 볼륨을 생성하기 전에 Cloud Volumes ONTAP 시스템에 키 관리 서비스가 올바르게 구성되어 있는지 확인하십시오. 이 구성은 FlexCache 볼륨이 원본 볼륨에서 데이터를 해독하는 데 필수적입니다.
. * 라이센스 *: Cloud Volumes ONTAP 시스템에서 유효한 FlexCache 라이센스가 사용 가능하고 활성화되어 있는지 확인합니다. BlueXP는 모든 신규 Cloud Volumes ONTAP 시스템에 대한 FlexCache 라이센스를 생성하며 사용 제한이 500GiB입니다.
. * ONTAP 버전 *: Cloud Volumes ONTAP 시스템의 ONTAP 버전이 암호화된 볼륨의 FlexCache를 지원하는지 확인하십시오. 자세한 내용은 최신 https://docs.netapp.com/us-en/ontap/release-notes/index.html["ONTAP 릴리즈 노트"^] 또는 호환성 매트릭스를 참조하십시오.
. * 네트워크 구성 *: 네트워크 구성이 오리진 볼륨과 FlexCache 볼륨 간의 원활한 통신을 허용하는지 확인합니다. 여기에는 클라우드 환경에서의 적절한 라우팅 및 DNS 확인이 포함됩니다.


.단계
암호화된 소스 볼륨으로 Cloud Volumes ONTAP 시스템에 FlexCache 볼륨을 생성합니다. 자세한 단계 및 추가 고려 사항은 다음 섹션을 참조하십시오.

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["빠른 데이터 액세스를 위한 FlexCache 볼륨 전원 가이드"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["System Manager에서 FlexCache 볼륨 생성"^]

