---
sidebar: sidebar 
permalink: task-managing-svms-azure.html 
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported 
summary: 스토리지 VM은 ONTAP 내에서 실행되는 가상 머신으로, 클라이언트에 스토리지 및 데이터 서비스를 제공합니다. SVM 또는 가상 서버로서 이를 알 수 있습니다. Cloud Volumes ONTAP는 기본적으로 하나의 스토리지 VM으로 구성되지만 일부 구성에서는 추가 스토리지 VM을 지원합니다. 
---
= Azure에서 Cloud Volumes ONTAP용 데이터 서비스 스토리지 VM을 관리합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
스토리지 VM은 ONTAP 내에서 실행되는 가상 머신으로, 클라이언트에 스토리지 및 데이터 서비스를 제공합니다. 이를 _SVM_ 또는 _vserver_로 알고 있을 수 있습니다. Cloud Volumes ONTAP는 기본적으로 하나의 스토리지 VM으로 구성되지만, Azure에서 Cloud Volumes ONTAP를 실행할 때 추가 스토리지 VM을 생성할 수 있습니다.

Azure에서 추가 데이터 제공 스토리지 VM을 생성 및 관리하려면 BlueXP  API를 사용해야 합니다. API가 스토리지 VM을 생성하고 필요한 네트워크 인터페이스를 구성하는 프로세스를 자동화하기 때문입니다. 스토리지 VM을 생성할 때 BlueXP 는 필요한 LIF 서비스와 스토리지 VM의 아웃바운드 SMB/CIFS 통신에 필요한 iSCSI LIF를 구성합니다.



== 지원되는 스토리지 VM 수입니다

Cloud Volumes ONTAP 9.9.0부터 라이센스에 따라 특정 구성으로 여러 스토리지 VM이 지원됩니다. 사용 중인 Cloud Volumes ONTAP 버전에 대해 지원되는 스토리지 VM 수를 확인하려면 를 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-azure.html["Cloud Volumes ONTAP 릴리즈 노트"^] 참조하십시오.

9.9.0 이전의 모든 Cloud Volumes ONTAP 버전은 하나의 데이터 서비스 스토리지 VM과 하나의 대상 스토리지 VM을 재해 복구에 사용합니다. 소스 스토리지 VM에 중단이 발생할 경우 데이터 액세스를 위해 대상 스토리지 VM을 활성화할 수 있습니다.

.시작하기 전에
Cloud Volumes ONTAP용 스토리지 VM을 생성하고 관리하려면 Connector에 특정 권한이 필요합니다. 필요한 권한은 에 포함되어 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html["NetApp에서 제공하는 정책"^] 있습니다.



== 스토리지 VM을 생성합니다

구성 및 라이센스 유형에 따라 BlueXP  API를 사용하여 단일 노드 시스템 또는 고가용성(HA) 구성에서 여러 스토리지 VM을 생성할 수 있습니다.

.이 작업에 대해
API를 사용하여 스토리지 VM을 생성하고 필요한 네트워크 인터페이스를 구성하는 경우 BlueXP 은 `default-data-files` NAS 데이터 LIF에서 다음 서비스를 제거한 후 아웃바운드 관리 연결에 사용되는 iSCSI 데이터 LIF에 추가하여 데이터 스토리지 VM의 정책을 수정합니다.

* `data-fpolicy-client`
* `management-ad-client`
* `management-dns-client`
* `management-ldap-client`
* `management-nis-client`




=== 단일 노드 시스템

다음 API 호출을 사용하여 단일 노드 시스템에 스토리지 VM을 생성하십시오.

`POST /azure/vsa/working-environments/{workingEnvironmentId}/svm`

요청 본문에는 다음이 포함되어야 합니다.

[source, json]
----
{ "svmName": "myNewSvm1"
   "svmPassword": "optional, the API takes the cluster password if not provided"
   "mgmtLif": "optional, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


=== HA 쌍

다음 API 호출을 사용하여 Azure HA 구성에서 스토리지 VM을 생성합니다.

`POST /azure/ha/working-environments/{workingEnvironmentId}/svm`

요청 본문에는 다음이 포함되어야 합니다.

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
   "mgmtLif": "optional value, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


== 단일 노드 시스템 및 HA 쌍에서 스토리지 VM을 관리합니다

BlueXP  API를 사용하면 단일 노드 및 HA 구성 모두에서 스토리지 VM의 이름을 바꾸고 삭제할 수 있습니다.



=== 스토리지 VM의 이름을 바꿉니다

스토리지 VM의 이름을 바꾸려면 기존 스토리지 VM과 새 스토리지 VM의 이름을 매개 변수로 제공해야 합니다.

.단계
* 다음 API 호출을 사용하여 단일 노드 시스템에서 스토리지 VM의 이름을 변경합니다.
+
`PUT /azure/vsa/working-environments/{workingEnvironmentId}/svm`

+
요청 본문에는 다음이 포함되어야 합니다.

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----
* HA 구성에서 스토리지 VM의 이름을 바꾸려면 다음 API 호출을 사용합니다.
+
`PUT /azure/ha/working-environments/{workingEnvironmentId}/svm`

+
요청 본문에는 다음이 포함되어야 합니다.

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----




=== 스토리지 VM을 삭제합니다

단일 노드 또는 HA 구성에서 액티브 볼륨이 없는 스토리지 VM을 제거할 수 있습니다.

.단계
* 다음 API 호출을 사용하여 단일 노드 시스템에서 스토리지 VM을 삭제합니다.
+
`DELETE /azure/vsa/working-environments/{workingEnvironmentId}/svm/{svmName}`

* 다음 API 호출을 사용하여 HA 구성에서 스토리지 VM을 삭제합니다.
+
`DELETE /azure/ha/working-environments/{workingEnvironmentId}/svm/{svmName}`


