---
sidebar: sidebar 
permalink: task-encrypting-volumes.html 
keywords: encrypt, encryption, data, volumes, netapp volume encryption, volume encryption, nve, key managers, kmip, key management servers, license, ssl certificates, nae, netapp aggregate encryption 
summary: 'Cloud Volumes ONTAP는 외부 키 관리자로 NVE(NetApp Volume Encryption) 및 NAE(NetApp Aggregate Encryption)를 지원합니다. 외부 키 관리자를 설정하면 NVE와 NAE가 기본적으로 활성화됩니다.' 
---
= NetApp 암호화 솔루션으로 볼륨 암호화
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Cloud Volumes ONTAP는 NVE(NetApp Volume Encryption) 및 NAE(NetApp Aggregate Encryption)를 지원합니다. NVE와 NAE는 FIPS 140-2를 준수하는 볼륨 유휴 데이터 암호화를 지원하는 소프트웨어 기반 솔루션입니다. link:concept-security.html["이러한 암호화 솔루션에 대해 자세히 알아보십시오"].

NVE와 NAE는 모두 외부 키 관리자로 지원됩니다.

ifdef::azure[]

endif::azure[]

ifdef::gcp[]

endif::gcp[]

외부 키 관리자를 설정한 후 새 애그리게이트에 NAE가 기본적으로 사용하도록 설정됩니다. NAE 애그리게이트에 속하지 않는 새로운 볼륨은 기본적으로 NVE를 사용하도록 설정됩니다(예: 외부 키 관리자를 설정하기 전에 생성된 기존 애그리게이트가 있는 경우).

Cloud Volumes ONTAP는 온보드 키 관리를 지원하지 않습니다.

.필요한 것
Cloud Volumes ONTAP 시스템은 NetApp 지원에 등록해야 합니다. NetApp 볼륨 암호화 라이센스는 NetApp Support에 등록된 각 Cloud Volumes ONTAP 시스템에 자동으로 설치됩니다.

* https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-adding-nss-accounts.html["BlueXP에 NetApp Support 사이트 계정 추가"^]
* link:task-registering.html["선불 종량제 시스템을 등록하는 중입니다"]



NOTE: BlueXP는 중국 지역에 있는 시스템에 NVE 라이센스를 설치하지 않습니다.

.단계
. 에서 지원되는 주요 관리자 목록을 검토합니다 http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^].
+

TIP: Key Managers * 솔루션을 검색합니다.

. link:task-connecting-to-otc.html["Cloud Volumes ONTAP CLI에 연결합니다"^].
. 외부 키 관리를 구성합니다.
+
ifdef::aws[]

+
** AWS: https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-external-key-management-overview-concept.html["자세한 내용은 ONTAP 설명서를 참조하십시오"^]




endif::aws[]

ifdef::azure[]

* Azure(Azure): link:task-azure-key-vault.html["Azure 키 저장소(AKV)"]


endif::azure[]

ifdef::gcp[]

* Google 클라우드: link:task-google-key-manager.html["Google Cloud 키 관리 서비스"]


endif::gcp[]
