---
sidebar: sidebar 
permalink: task-verify-autosupport.html 
keywords: autosupport, set up autosupport, test autosupport, asup, test asup 
summary: AutoSupport은 능동적으로 시스템 상태를 모니터링하고 NetApp 기술 지원 팀에 메시지를 보냅니다. 기본적으로 AutoSupport는 각 노드에서 HTTPS 전송 프로토콜을 사용하여 기술 지원 부서에 메시지를 보내도록 설정됩니다. AutoSupport에서 이러한 메시지를 보낼 수 있는지 확인하는 것이 가장 좋습니다. 
---
= AutoSupport 설정을 확인합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AutoSupport은 능동적으로 시스템 상태를 모니터링하고 NetApp 기술 지원 팀에 메시지를 보냅니다. 기본적으로 AutoSupport는 각 노드에서 HTTPS 전송 프로토콜을 사용하여 기술 지원 부서에 메시지를 보내도록 설정됩니다. AutoSupport에서 이러한 메시지를 보낼 수 있는지 확인하는 것이 가장 좋습니다.

필요한 유일한 구성 단계는 Cloud Volumes ONTAP가 아웃바운드 인터넷 연결을 사용할 수 있도록 하는 것입니다. 자세한 내용은 해당 클라우드 공급자의 네트워킹 요구 사항을 참조하십시오.



== AutoSupport 요구 사항

Cloud Volumes ONTAP 노드를 사용하려면 NetApp AutoSupport에 대한 아웃바운드 인터넷 액세스가 필요합니다. 사전 예방적으로 시스템의 상태를 모니터링하고 메시지를 NetApp 기술 지원으로 보냅니다.

라우팅 및 방화벽 정책은 Cloud Volumes ONTAP가 AutoSupport 메시지를 보낼 수 있도록 다음 엔드포인트에 대한 HTTP/HTTPS 트래픽을 허용해야 합니다.

* https://support.netapp.com/aods/asupmessage 으로 문의하십시오
* https://support.netapp.com/asupprod/post/1.0/postAsup 으로 문의하십시오


AutoSupport 메시지를 보내는 데 아웃바운드 인터넷 연결을 사용할 수 없는 경우 BlueXP는 자동으로 Cloud Volumes ONTAP 시스템에서 커넥터를 프록시 서버로 사용하도록 구성합니다. 유일한 요구 사항은 커넥터의 보안 그룹이 포트 3128을 통한 _IN인바운드_연결을 허용하는지 확인하는 것입니다. Connector를 배포한 후 이 포트를 열어야 합니다.

Cloud Volumes ONTAP에 대해 엄격한 아웃바운드 규칙을 정의한 경우 Cloud Volumes ONTAP 보안 그룹이 포트 3128을 통한 _outbound_connection을 허용하는지 확인해야 합니다.

아웃바운드 인터넷 액세스가 가능한지 확인한 후 AutoSupport를 테스트하여 메시지를 보낼 수 있는지 확인할 수 있습니다. 자세한 내용은 을 https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html["ONTAP 설명서: AutoSupport 설치"^]참조하십시오.



== AutoSupport 구성 문제를 해결합니다

아웃바운드 연결을 사용할 수 없고 BlueXP에서 커넥터를 프록시 서버로 사용하도록 Cloud Volumes ONTAP 시스템을 구성할 수 없는 경우 "<작업 환경 이름>이(가) AutoSupport 메시지를 보낼 수 없습니다."라는 제목의 BlueXP에서 알림을 받게 됩니다.

네트워킹 문제로 인해 이 메시지가 표시될 가능성이 높습니다.

이 문제를 해결하려면 다음 단계를 수행하십시오.

.단계
. Cloud Volumes ONTAP ONTAP CLI에서 시스템을 관리할 수 있도록 SSH 시스템에 연결합니다.
+
link:task-connecting-to-otc.html["Cloud Volumes ONTAP에 SSH를 사용하는 방법에 대해 알아보십시오"].

. AutoSupport 하위 시스템의 세부 상태를 표시합니다.
+
AutoSupport check show-details를 선택합니다

+
응답은 다음과 비슷해야 합니다.

+
[listing]
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
http-https 범주의 상태가 "ok"이면 AutoSupport가 올바르게 구성되어 메시지를 보낼 수 있음을 의미합니다.

. 상태가 정상이 아닌 경우 각 Cloud Volumes ONTAP 노드의 프록시 URL을 확인합니다.
+
AutoSupport show-fields proxy-url

. 프록시 URL 매개 변수가 비어 있는 경우 Cloud Volumes ONTAP에서 커넥터를 프록시로 사용하도록 구성합니다.
+
AutoSupport modify-proxy-url\http://<connector private ip>:3128

. AutoSupport 상태 다시 확인:
+
AutoSupport check show-details를 선택합니다

. 상태가 여전히 FAILED인 경우 Cloud Volumes ONTAP와 포트 3128을 통한 커넥터 사이에 연결이 있는지 확인합니다.
. 연결이 있는지 확인한 후에도 상태 ID가 계속 실패하면 커넥터에 SSH를 연결합니다.
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#connect-to-the-linux-vm["Connector용 Linux VM에 연결하는 방법에 대해 자세히 알아보십시오"^]

. '/opt/application/netapp/cloudmanager/docker_occm/data/'로 이동합니다
. 프록시 구성 파일 'quid.conf'를 엽니다
+
파일의 기본 구조는 다음과 같습니다.

+
[listing]
----
        http_port 3128
        acl localnet src 172.31.0.0/16
        acl azure_aws_metadata dst 169.254.169.254

        http_access allow localnet
        http_access deny azure_aws_metadata
        http_access allow localhost
        http_access deny all
----
+
localnet src 값은 Cloud Volumes ONTAP 시스템의 CIDR입니다.

. Cloud Volumes ONTAP 시스템의 CIDR 블록이 파일에 지정된 범위에 있지 않으면 다음과 같이 값을 업데이트하거나 새 항목을 추가합니다.
+
'ACL cvonet src <CIDR>'

+
이 새 항목을 추가하는 경우 허용 항목도 추가해야 합니다.

+
http_access allow cvonet'입니다

+
예를 들면 다음과 같습니다.

+
[listing]
----
        http_port 3128
        acl localnet src 172.31.0.0/16
        acl cvonet src 172.33.0.0/16
        acl azure_aws_metadata dst 169.254.169.254

        http_access allow localnet
        http_access allow cvonet
        http_access deny azure_aws_metadata
        http_access allow localhost
        http_access deny all
----
. 구성 파일을 편집한 후 프록시 컨테이너를 sudo로 다시 시작합니다.
+
'오징어 재가동

. Cloud Volumes ONTAP CLI로 돌아가서 Cloud Volumes ONTAP가 AutoSupport 메시지를 보낼 수 있는지 확인합니다.
+
AutoSupport check show-details를 선택합니다


