---
sidebar: sidebar 
permalink: task-convert-node-capacity.html 
keywords: license conversion, convert node-based to capacity based, by-node to by-capacity, bluexp license conversion for node based 
summary: '노드 기반 라이센스의 EOA(End of Availability)가 완료되면 BlueXP  라이센스 변환 툴을 사용하여 용량 기반 라이센스로 전환해야 합니다.' 
---
= 노드 기반 라이센스를 용량 기반으로 변환
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
노드 기반 라이센스의 EOA(End of Availability)가 완료되면 BlueXP  라이센스 변환 툴을 사용하여 용량 기반 라이센스로 전환해야 합니다.

연간 또는 장기 약정의 경우 NetApp, 전환을 위한 사전 요구사항이 충족되는지 확인하기 위해 EOA 날짜(2024년 11월 11일) 또는 라이센스 만료일 전에 NetApp 담당자에게 연락하는 것이 좋습니다. Cloud Volumes ONTAP 노드에 대한 장기 계약이 없고 온디맨드 용량제(PAYGO) 구독에 대해 시스템을 실행하는 경우, 2024년 12월 31일 EOS(지원 종료) 전에 전환을 계획하는 것이 중요합니다. 두 경우 모두 원활한 전환을 위해 BlueXP  라이센스 변환 도구를 사용하기 전에 시스템이 요구 사항을 충족하는지 확인해야 합니다.

EOA 및 EOS에 대한 자세한 내용은 을 link:concept-licensing.html#end-of-availability-of-node-based-licenses["노드 기반 라이센스의 공급 중지"]참조하십시오.

.이 작업에 대해
* 라이센스 변환 툴을 사용하면 데이터를 마이그레이션하거나 추가 클라우드 리소스를 프로비저닝할 필요가 없이 노드 기반 라이센스 모델에서 용량 기반 라이센스 모델로 전환할 수 있습니다.
* 무중단 운영이며 서비스 중단이나 애플리케이션 다운타임이 발생하지 않습니다.
* Cloud Volumes ONTAP 시스템의 계정 및 응용 프로그램 데이터는 그대로 유지됩니다.
* 기본 클라우드 리소스는 변환 후 영향을 받지 않습니다.
* 라이센스 변환 도구는 단일 노드, 단일 가용 영역(AZ)의 HA(고가용성), 다중 AZ의 HA, BYOL(Bring Your Own License) 및 PAYGO와 같은 모든 배포 유형을 지원합니다.
* 이 툴은 모든 노드 기반 라이센스를 소스로, 모든 용량 기반 라이센스를 대상으로 지원합니다. 예를 들어, PAYGO Standard 노드 기반 라이센스가 있는 경우 BYOL 용량 기반 라이센스로 변환할 수 있습니다.
* 변환은 모든 클라우드 공급자, AWS, Azure 및 Google Cloud에서 지원됩니다.
* 변환 후 노드 기반 라이센스의 일련 번호가 용량 기반 형식으로 교체됩니다. 이 작업은 변환의 일부로 수행되며 NetApp 지원 사이트(NSS) 계정에 반영됩니다.
* 용량 기반 모델로 전환해도 노드 기반 라이센스와 동일한 위치에 데이터가 계속 유지됩니다. 이런 접근 방식은 데이터 배치의 중단을 보장하고 전환 과정에서 데이터 주권 원칙을 유지합니다.


.시작하기 전에
* 고객 액세스 또는 관리자 액세스 권한이 있는 NSS 계정이 있어야 합니다.
* NSS 계정은 BlueXP  사용자 자격 증명으로 등록해야 합니다.
* 작업 환경은 고객 액세스 또는 관리자 액세스 권한이 있는 NSS 계정에 연결되어야 합니다.
* BYOL 라이센스 또는 마켓플레이스 가입과 같은 유효한 용량 기반 라이센스가 있어야 합니다.
* 용량 기반 라이센스는 BlueXP  계정에서 사용할 수 있어야 합니다. 이 라이센스는 마켓플레이스 구독 또는 BlueXP  디지털 지갑의 BYOL/전용 혜택 패키지가 될 수 있습니다.
* 대상 패키지를 선택하기 전에 다음 기준을 이해해야 합니다.
+
** 계정에 용량 기반 BYOL 라이센스가 있는 경우 선택한 대상 패키지가 계정의 BYOL 용량 기반 라이센스와 일치해야 합니다.
+
*** 가 대상 패키지로 선택된 경우 `Professional` 계정에 Professional 패키지가 있는 BYOL 라이센스가 있어야 합니다.
*** 가 대상 패키지로 선택된 경우 `Essentials`, 계정에 Essentials 패키지가 있는 BYOL 라이센스가 있어야 합니다.
*** 가 대상 패키지로 선택된 경우 `Optimized`, 계정에 최적화된 패키지가 있는 BYOL 라이센스가 있어야 합니다.


** 대상 패키지가 계정의 BYOL 라이선스 사용 가능 여부와 일치하지 않는 경우 용량 기반 라이센스에 선택한 패키지가 포함되지 않을 수 있음을 의미합니다. 이 경우 마켓플레이스 가입을 통해 비용이 청구됩니다.
** 용량 기반 BYOL 라이센스는 없지만 마켓플레이스 구독만 있는 경우 선택한 패키지가 용량 기반 마켓플레이스 구독에 포함되어 있는지 확인해야 합니다.
** 기존 용량 기반 라이센스에 충분한 용량이 없고 추가 용량 사용을 청구할 수 있는 마켓플레이스 가입이 있는 경우 마켓플레이스 가입을 통해 추가 용량에 대한 요금이 청구됩니다.
** 기존 용량 기반 라이센스에 충분한 용량이 없고 추가 용량 사용을 청구할 수 있는 마켓플레이스 구독이 없는 경우 변환이 수행되지 않습니다. 마켓플레이스 가입을 추가하여 추가 용량을 청구하거나 사용 가능한 용량을 현재 라이센스로 확장해야 합니다.
** 대상 패키지가 계정의 BYOL 라이선스 사용 가능 여부와 기존 용량 기반 라이선스의 용량이 충분하지 않은 경우 마켓플레이스 가입을 통해 비용이 청구됩니다.





NOTE: 이러한 요구 사항이 충족되지 않으면 라이센스 변환이 수행되지 않습니다. 특정 경우에는 라이센스가 변환될 수 있지만 사용할 수 없습니다. 정보 아이콘을 클릭하여 문제를 식별하고 수정 조치를 취하십시오.

.단계
. Canvas 페이지에서 라이센스 유형을 수정하려는 작업 환경의 이름을 두 번 클릭합니다.
. 개요 탭에서 기능 패널을 클릭합니다.
. 충전 방법 * 옆에 있는 연필 아이콘을 확인합니다. 시스템의 충전 방법이 인 경우 `Node Based` 용량 기준 충전으로 전환할 수 있습니다.
+

TIP: Cloud Volumes ONTAP 시스템이 이미 용량 단위로 충전되어 있거나 요구 사항을 충족하지 않는 경우 아이콘이 비활성화됩니다.

. 노드 기반 라이센스를 용량 기반으로 변환 * 화면에서 작업 환경 이름 및 소스 라이센스 세부 정보를 확인합니다.
. 기존 라이센스를 변환할 대상 패키지를 선택합니다.
+
** 필수 요소입니다. 기본값은 입니다 `Essentials`.
** 전문가입니다




ifdef::azure[]

* 최적화됨(Azure용)


endif::azure[]

ifdef::gcp[]

* 최적화됨(Google Cloud용)


endif::gcp[]

. BYOL 라이센스가 있는 경우 확인란을 선택하여 BlueXP  디지털 지갑에서 전환 후 노드 기반 라이센스를 삭제할 수 있습니다. 변환이 완료되지 않은 경우 이 확인란을 선택해도 디지털 지갑에서 라이센스가 삭제되지 않습니다. 마켓플레이스 가입이 있는 경우 이 옵션을 사용할 수 없습니다.
. 확인란을 선택하여 변경의 의미를 이해했음을 확인한 다음 * Proceed * 를 클릭합니다.


.작업을 마친 후
새 라이센스 일련 번호를 확인하고 BlueXP  디지털 지갑의 변경 사항을 확인합니다.
