= BlueXP 에서 System Manager에 액세스할 수 있도록 사용자 인증을 설정했습니다
:allow-uri-read: 




=== BlueXP 에서 System Manager에 액세스할 수 있도록 사용자 인증을 설정했습니다

이제 BlueXP  관리자는 BlueXP 에서 ONTAP System Manager에 액세스하는 ONTAP 사용자에 대해 인증을 활성화할 수 있습니다. BlueXP  커넥터 설정을 편집하여 이 옵션을 활성화할 수 있습니다. 이 옵션은 표준 및 개인 모드에서 사용할 수 있습니다.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-administer-advanced-view.html["System Manager를 사용하여 Cloud Volumes ONTAP를 관리합니다"^]..



=== BlueXP  고급 보기의 이름이 System Manager로 바뀌었습니다

BlueXP 에서 ONTAP 시스템 관리자를 통해 Cloud Volumes ONTAP의 고급 관리 옵션이 * 고급 보기 * 에서 * 시스템 관리자 * 로 변경되었습니다.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-administer-advanced-view.html["System Manager를 사용하여 Cloud Volumes ONTAP를 관리합니다"^]..



=== BlueXP  디지털 지갑으로 라이선스를 관리하는 간단한 방법을 소개합니다

이제 BlueXP  디지털 지갑의 향상된 탐색 지점을 사용하여 Cloud Volumes ONTAP 라이선스 관리를 간소화할 수 있습니다.

* 거버넌스 > 디지털 지갑 > 개요/직접 라이센스 * 탭을 통해 Cloud Volumes ONTAP 라이센스 정보에 쉽게 액세스할 수 있습니다.
* 개요 * 탭의 Cloud Volume ONTAP 패널에서 * 보기 * 를 클릭하면 용량 기반 라이센스에 대한 포괄적인 이해를 얻을 수 있습니다. 이 고급 보기는 라이선스 및 구독에 대한 자세한 정보를 제공합니다.
* 이전 인터페이스를 선호하는 경우 * 레거시 보기로 전환 * 버튼을 클릭하여 유형별로 라이센스 세부 정보를 보고 라이센스에 대한 청구 방법을 수정할 수 있습니다.


link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html["용량 기반 라이센스 관리"^]..
